"""Analyst (Subagent D): technical writeup from merged metrics.

Produces `artifacts/technical_writeup.md` judged against
`brain/examples/pareto_example.md` by the Eval Loop's taste gate.

Usage:
    python scripts/generate_writeup.py [--input artifacts/raw_metrics.json] \\
        [--output artifacts/technical_writeup.md]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from harness.metrics import pareto_optimal


def _fmt(x, unit: str = "") -> str:
    if x is None:
        return "—"
    return f"{x:,.2f} {unit}".strip() if isinstance(x, float) else f"{x} {unit}".strip()


def generate_writeup(metrics_path: Path, out_path: Path) -> str:
    metrics = json.loads(Path(metrics_path).read_text(encoding="utf-8"))
    quant = metrics.get("quantization", [])
    spec = metrics.get("speculative", [])
    mode, seed = metrics.get("mode", "?"), metrics.get("seed", "?")

    tps_winner = max(quant, key=lambda r: r["tokens_per_sec"])
    mem_winner = min(quant, key=lambda r: r["mem_gb"])
    speed_rows = [r for r in spec if r.get("speedup_vs_baseline") is not None]
    speed_winner = max(speed_rows, key=lambda r: r["speedup_vs_baseline"]) if speed_rows else None

    # Frontier axes match the chart: max throughput, min memory, min latency,
    # min quality cost (PPL).
    idx = pareto_optimal(
        quant,
        maximize=("tokens_per_sec",),
        minimize=("mem_gb", "latency_ms_mean", "quality_ppl"),
    )
    frontier = [quant[i] for i in idx]
    frontier_names = {r["method"] for r in frontier}

    lines: list[str] = []
    lines.append("# Technical Writeup — Quantization & Speculative Decoding Benchmarking Engine")
    lines.append("")
    lines.append(
        f"> Generated by `orchestrator/pipeline.py` — mode=`{mode}`, seed=`{seed}`. "
        "All numbers below are traceable to `artifacts/raw_metrics.json`."
    )
    lines.append("")

    lines.append("## 1. Key findings")
    lines.append("")
    lines.append(f"- **Throughput winner:** `{tps_winner['method']}` ({tps_winner['bits']}-bit) reaches "
                 f"**{_fmt(tps_winner['tokens_per_sec'], 'tok/s')}** at **{_fmt(tps_winner['mem_gb'], 'GB')}** "
                 f"— the strongest frontier point for latency-critical serving.")
    lines.append(f"- **Memory winner:** `{mem_winner['method']}` ({mem_winner['bits']}-bit) uses "
                 f"**{_fmt(mem_winner['mem_gb'], 'GB')}** with a quality cost of "
                 f"ΔPPL **+{max(0.0, round(mem_winner['quality_ppl'] - min(r['quality_ppl'] for r in quant), 2))}** vs the FP16 baseline.")
    if speed_winner:
        lines.append(f"- **Speculative decoding:** `{speed_winner['method']}` ({speed_winner['draft']} → {speed_winner['target']}) "
                     f"reaches **{_fmt(speed_winner['speedup_vs_baseline'], '×')}** tokens/s on `{speed_winner['domain']}` "
                     f"at acceptance rate **{_fmt(speed_winner['acceptance_rate'])}** (γ={speed_winner['gamma']}).")
    lines.append("")

    lines.append("## 2. Quantization matrix")
    lines.append("")
    lines.append("| Method | Bits | Throughput (tok/s) | Mem (GB) | Latency (ms/tok) | ΔPPL vs FP16 | On frontier? |")
    lines.append("| --- | --- | ---: | ---: | ---: | ---: | --- |")
    base_ppl = min(r["quality_ppl"] for r in quant)
    for r in sorted(quant, key=lambda x: x["tokens_per_sec"], reverse=True):
        dppl = r["quality_ppl"] - base_ppl
        lines.append(
            f"| {r['method']} | {r['bits']} | {_fmt(r['tokens_per_sec'])} | {_fmt(r['mem_gb'])} | "
            f"{_fmt(r.get('latency_ms_mean'))} | +{dppl:.2f} | {'**yes**' if r['method'] in frontier_names else 'no'} |"
        )
    lines.append("")

    lines.append("## 3. Pareto frontier")
    lines.append("")
    lines.append("The frontier is the set of configurations not dominated on throughput, memory, latency, or quality:")
    lines.append("")
    lines.append("| Method | Bits | Throughput (tok/s) | Mem (GB) |")
    lines.append("| --- | --- | ---: | ---: | --- |")
    for r in sorted(frontier, key=lambda x: x["mem_gb"]):
        lines.append(f"| {r['method']} | {r['bits']} | {_fmt(r['tokens_per_sec'])} | {_fmt(r['mem_gb'])} |")
    lines.append("")
    dominated = [r for r in quant if r["method"] not in frontier_names]
    if dominated:
        lines.append("Dominated points (explained):")
        for r in dominated:
            lines.append(f"- `{r['method']}` is dominated by a configuration with ≤ memory and ≥ throughput.")
    lines.append("")

    lines.append("## 4. Speculative decoding")
    lines.append("")
    lines.append("Speedup vs the target-only baseline, per domain. Acceptance rate is reported alongside every speedup.")
    lines.append("")
    pairs = {}
    for r in spec:
        key = (r["method"], r.get("draft"), r["gamma"])
        pairs.setdefault(key, []).append(r)
    for key, rows in pairs.items():
        method, draft, gamma = key
        lines.append(f"### {method}" + (f" ({draft} → {rows[0]['target']}, γ={gamma})" if draft else ""))
        lines.append("")
        lines.append("| Domain | Throughput (tok/s) | Acceptance | Speedup |")
        lines.append("| --- | ---: | ---: | ---: |")
        for r in rows:
            lines.append(f"| {r['domain']} | {_fmt(r['tokens_per_sec'])} | {_fmt(r['acceptance_rate'])} | {_fmt(r['speedup_vs_baseline'], '×')} |")
        lines.append("")

    lines.append("## 5. Provenance & reproducibility")
    lines.append("")
    lines.append(f"- **Mode:** `{mode}` (seed `{seed}`, {metrics.get('num_runs', '?')} runs/config)")
    lines.append(f"- **Generated:** {metrics.get('generated_at', '?')}")
    lines.append(f"- **System:** python {metrics.get('system', {}).get('python', '?')}, cwd {metrics.get('system', {}).get('cwd', '?')}")
    lines.append("- Simulated priors are seeded and deterministic; live runs require a GPU host "
                 "(`requirements-live.txt`) and record real provenance.")
    lines.append("- Re-run everything: `python -m orchestrator.pipeline --mode simulate`")
    lines.append("")

    text = "\n".join(lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"[writeup] saved: {out_path} ({len(text.split())} words)")
    return text


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate the technical writeup")
    parser.add_argument("--input", default="artifacts/raw_metrics.json")
    parser.add_argument("--output", default="artifacts/technical_writeup.md")
    args = parser.parse_args()
    generate_writeup(Path(args.input), Path(args.output))
